# Generated by Django 4.2.5 on 2023-09-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_room_content_type_room_object_id_mathgame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
