# Generated by Django 5.0.6 on 2024-07-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_mathgame_game_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='game_session',
        ),
        migrations.RemoveField(
            model_name='gamesessiongame',
            name='session',
        ),
        migrations.RemoveField(
            model_name='gamesessiongame',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='mathgame',
            name='room',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='GameScore',
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.DeleteModel(
            name='GameSession',
        ),
        migrations.DeleteModel(
            name='GameSessionGame',
        ),
        migrations.DeleteModel(
            name='MathGame',
        ),
    ]
