# Generated by Django 5.0.6 on 2024-07-02 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_leaderboard_game_session_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
