# Generated by Django 5.0.6 on 2024-07-12 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_mathgame'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='game_id',
            field=models.IntegerField(default=0),
        ),
    ]
